### ISSUE TITLE
The amount shown in the membership detail is not the good one

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#117]
# Scenario
Case 1 : Go the member list then go to a member's profile and finally go to the membership tab.
Case 2 : Go to the memberships list then go to a membership detail.

# Expected behavior
The payment amount shown is the sum of the membership and donation amounts.

# Current behavior
We should only show the membership amount and rename the label accordingly.

**Comment by LucileDT** [comment]
I do not agree with you on this one: the Payment amount (in green in the screenshot) is indeed the membership+donation one, so the amount of the payment is correct in my point of view (although that's why we display the membership cost beside its name, is pink in the screenshot)

![image](https://user-images.githubusercontent.com/23707217/73592275-b48dee00-44f8-11ea-99be-ec69d0fe2934.png)


I think we should rework those frames to link to:
- the payment
- the donation if there is one

**Comment by Yann-BUTSCHER-EIRL** [comment]
Okay your point is fair. You can go on with the changes.

**Comment by LucileDT** [comment]
![image](https://user-images.githubusercontent.com/23707217/74143929-0969ec80-4bfc-11ea-93b4-8b5d1e83bd96.png)
Fixing the membership details page to add between braces the amount of the membership just after the title of the membership.

**Comment by LucileDT** [comment]
@Parmifer could you please test it?

**Comment by Yann-BUTSCHER-EIRL** [comment]
Fix validated. Closing.
